[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "ALLOW-FROM https://main--classy-monstera-b42bc3.netlify.app/"
    X-Frame-Options = "ALLOW-FROM https://mellow-platypus-c20d1e.netlify.app"

[[headers]]
  for = "/*.wasm"
    [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/*.wasm.map"
    [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"