[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "ALLOW-FROM https://tu-sitio-web.com"
    
[[headers]]
  for = "/*.wasm"
    [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/*.wasm.map"
    [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"